Fix many type errors (15 of 18) due to types missing a discriminator
Before:
```
yarn run v1.22.19
modules/enhancedEcommerceEvents.ts:48:27 - error TS2339: Property 'list' does not exist on type 'ProductViewData | PromoViewData | PromotionClickData'.
  Property 'list' does not exist on type 'PromoViewData'.

48       const list = e.data.list ? { actionField: { list: e.data.list } } : {}
                             ~~~~

modules/enhancedEcommerceEvents.ts:48:64 - error TS2339: Property 'list' does not exist on type 'ProductViewData | PromoViewData | PromotionClickData'.
  Property 'list' does not exist on type 'PromoViewData'.

48       const list = e.data.list ? { actionField: { list: e.data.list } } : {}
                                                                  ~~~~

modules/enhancedEcommerceEvents.ts:105:27 - error TS2339: Property 'list' does not exist on type 'ProductClickData | PromoViewData | PromotionClickData'.
  Property 'list' does not exist on type 'PromoViewData'.

105       const list = e.data.list ? { actionField: { list: e.data.list } } : {}
                              ~~~~

modules/enhancedEcommerceEvents.ts:105:64 - error TS2339: Property 'list' does not exist on type 'ProductClickData | PromoViewData | PromotionClickData'.
  Property 'list' does not exist on type 'PromoViewData'.

105       const list = e.data.list ? { actionField: { list: e.data.list } } : {}
                                                                   ~~~~

modules/enhancedEcommerceEvents.ts:213:46 - error TS2345: Argument of type 'OrderPlacedData | PromoViewData | PromotionClickData' is not assignable to parameter of type 'Order'.
  Type 'PromoViewData' is missing the following properties from type 'Order': accountName, corporateName, coupon, openTextField, and 27 more.

213           actionField: getPurchaseObjectData(order),
                                                 ~~~~~

modules/enhancedEcommerceEvents.ts:214:27 - error TS2339: Property 'transactionProducts' does not exist on type 'OrderPlacedData | PromoViewData | PromotionClickData'.
  Property 'transactionProducts' does not exist on type 'PromoViewData'.

214           products: order.transactionProducts.map((product: ProductOrder) =>
                              ~~~~~~~~~~~~~~~~~~~

modules/enhancedEcommerceEvents.ts:241:25 - error TS2339: Property 'list' does not exist on type 'ProductImpressionData | PromoViewData | PromotionClickData'.

241       const { currency, list, impressions } = e.data
                            ~~~~

modules/enhancedEcommerceEvents.ts:241:31 - error TS2339: Property 'impressions' does not exist on type 'ProductImpressionData | PromoViewData | PromotionClickData'.

241       const { currency, list, impressions } = e.data
                                  ~~~~~~~~~~~

modules/enhancedEcommerceEvents.ts:261:15 - error TS2339: Property 'orderForm' does not exist on type 'PromoViewData | PromotionClickData'.

261       const { orderForm } = e.data
                  ~~~~~~~~~

modules/extraEvents.ts:19:26 - error TS2339: Property 'pageUrl' does not exist on type 'PageViewData | PromoViewData | PromotionClickData'.
  Property 'pageUrl' does not exist on type 'PromoViewData'.

19         location: e.data.pageUrl,
                            ~~~~~~~

modules/extraEvents.ts:20:22 - error TS2339: Property 'pageUrl' does not exist on type 'PageViewData | PromoViewData | PromotionClickData'.
  Property 'pageUrl' does not exist on type 'PromoViewData'.

20         page: e.data.pageUrl.replace(e.origin, ''),
                        ~~~~~~~

modules/extraEvents.ts:21:26 - error TS2339: Property 'referrer' does not exist on type 'PageViewData | PromoViewData | PromotionClickData'.
  Property 'referrer' does not exist on type 'PromoViewData'.

21         referrer: e.data.referrer,
                            ~~~~~~~~

modules/extraEvents.ts:22:20 - error TS2339: Property 'pageTitle' does not exist on type 'PageViewData | PromoViewData | PromotionClickData'.
  Property 'pageTitle' does not exist on type 'PromoViewData'.

22         ...(e.data.pageTitle && {
                      ~~~~~~~~~

modules/extraEvents.ts:23:25 - error TS2339: Property 'pageTitle' does not exist on type 'PageViewData | PromoViewData | PromotionClickData'.
  Property 'pageTitle' does not exist on type 'PromoViewData'.

23           title: e.data.pageTitle,
                           ~~~~~~~~~

modules/extraEvents.ts:33:17 - error TS2339: Property 'isAuthenticated' does not exist on type 'UserData | PromoViewData | PromotionClickData'.
  Property 'isAuthenticated' does not exist on type 'PromoViewData'.

33       if (!data.isAuthenticated) {
                   ~~~~~~~~~~~~~~~

modules/extraEvents.ts:37:30 - error TS2339: Property 'email' does not exist on type 'UserData | PromoViewData | PromotionClickData'.
  Property 'email' does not exist on type 'PromoViewData'.

37       const emailHash = data.email ? await emailToHash(data.email) : undefined
                                ~~~~~

modules/extraEvents.ts:37:61 - error TS2339: Property 'email' does not exist on type 'UserData | PromoViewData | PromotionClickData'.
  Property 'email' does not exist on type 'PromoViewData'.

37       const emailHash = data.email ? await emailToHash(data.email) : undefined
                                                               ~~~~~

modules/extraEvents.ts:41:22 - error TS2339: Property 'id' does not exist on type 'UserData | PromoViewData | PromotionClickData'.
  Property 'id' does not exist on type 'PromoViewData'.

41         userId: data.id,
                        ~~

Found 18 errors.
```

After:
```
yarn run v1.22.19
modules/enhancedEcommerceEvents.ts:260:10 - error TS2678: Type '"vtex:cartLoaded"' is not comparable to type '"vtex:productView" | "vtex:productClick" | "vtex:orderPlaced" | "vtex:orderPlacedTracked" | "vtex:pageView" | "vtex:pageInfo" | "vtex:productImpression" | "vtex:addToCart" | ... 4 more ... | "vtex:promoView"'.

260     case 'vtex:cartLoaded': {
             ~~~~~~~~~~~~~~~~~

modules/enhancedEcommerceEvents.ts:270:33 - error TS2339: Property 'items' does not exist on type 'never'.

270             products: orderForm.items.map(getCheckoutProductObjectData),
                                    ~~~~~

modules/enhancedEcommerceEvents.ts:297:10 - error TS2678: Type '"vtex:promotionClick"' is not comparable to type '"vtex:productView" | "vtex:productClick" | "vtex:orderPlaced" | "vtex:orderPlacedTracked" | "vtex:pageView" | "vtex:pageInfo" | "vtex:productImpression" | "vtex:addToCart" | ... 4 more ... | "vtex:promoView"'.

297     case 'vtex:promotionClick': {
             ~~~~~~~~~~~~~~~~~~~~~

Found 3 errors.
```