Fix type error, we cannot use `position` for the item's index
See https://master--vtex.myvtex.com/admin/builder-log/build-log-viewer/09e65bb6613045548a3fa7a7574d992b:

```
[at-loader] ../../.../react/modules/gaEvents.ts:30:36
TS2339: Property 'position' does not exist on type 'ProductViewData'.
```

Typing the event payload uncovered we don't have access to the `position` property.