Fix type errors (2 of 3)
Before:
```
yarn run v1.22.19
modules/enhancedEcommerceEvents.ts:260:10 - error TS2678: Type '"vtex:cartLoaded"' is not comparable to type '"vtex:productView" | "vtex:productClick" | "vtex:orderPlaced" | "vtex:orderPlacedTracked" | "vtex:pageView" | "vtex:pageInfo" | "vtex:productImpression" | "vtex:addToCart" | ... 4 more ... | "vtex:promoView"'.

260     case 'vtex:cartLoaded': {
             ~~~~~~~~~~~~~~~~~

modules/enhancedEcommerceEvents.ts:270:33 - error TS2339: Property 'items' does not exist on type 'never'.

270             products: orderForm.items.map(getCheckoutProductObjectData),
                                    ~~~~~

modules/enhancedEcommerceEvents.ts:297:10 - error TS2678: Type '"vtex:promotionClick"' is not comparable to type '"vtex:productView" | "vtex:productClick" | "vtex:orderPlaced" | "vtex:orderPlacedTracked" | "vtex:pageView" | "vtex:pageInfo" | "vtex:productImpression" | "vtex:addToCart" | ... 4 more ... | "vtex:promoView"'.

297     case 'vtex:promotionClick': {
             ~~~~~~~~~~~~~~~~~~~~~

Found 3 errors.
```

After:
```
yarn run v1.22.19
modules/enhancedEcommerceEvents.ts:297:10 - error TS2678: Type '"vtex:promotionClick"' is not comparable to type '"vtex:productView" | "vtex:productClick" | "vtex:orderPlaced" | "vtex:orderPlacedTracked" | "vtex:pageView" | "vtex:pageInfo" | "vtex:productImpression" | "vtex:addToCart" | ... 5 more ... | "vtex:promoView"'.

297     case 'vtex:promotionClick': {
             ~~~~~~~~~~~~~~~~~~~~~

Found 1 error.
```