Merge squash `chore/remove-unused-type`
commit 10feae5893fac2d5c7935adb4e54e88bb10a1d4f
Author: Filipe W. Lima <381395+filipewl@users.noreply.github.com>
Date:   Tue Apr 25 19:18:12 2023 -0300

    Fix last type error

commit b9c49f756ccbadaacc1fb1a0edf147c38981a5da
Author: Filipe W. Lima <381395+filipewl@users.noreply.github.com>
Date:   Tue Apr 25 19:16:30 2023 -0300

    Fix type errors (2 of 3)

    Before:
    ```
    yarn run v1.22.19
    modules/enhancedEcommerceEvents.ts:260:10 - error TS2678: Type '"vtex:cartLoaded"' is not comparable to type '"vtex:productView" | "vtex:productClick" | "vtex:orderPlaced" | "vtex:orderPlacedTracked" | "vtex:pageView" | "vtex:pageInfo" | "vtex:productImpression" | "vtex:addToCart" | ... 4 more ... | "vtex:promoView"'.

    260     case 'vtex:cartLoaded': {
                 ~~~~~~~~~~~~~~~~~

    modules/enhancedEcommerceEvents.ts:270:33 - error TS2339: Property 'items' does not exist on type 'never'.

    270             products: orderForm.items.map(getCheckoutProductObjectData),
                                        ~~~~~

    modules/enhancedEcommerceEvents.ts:297:10 - error TS2678: Type '"vtex:promotionClick"' is not comparable to type '"vtex:productView" | "vtex:productClick" | "vtex:orderPlaced" | "vtex:orderPlacedTracked" | "vtex:pageView" | "vtex:pageInfo" | "vtex:productImpression" | "vtex:addToCart" | ... 4 more ... | "vtex:promoView"'.

    297     case 'vtex:promotionClick': {
                 ~~~~~~~~~~~~~~~~~~~~~

    Found 3 errors.
    ```

    After:
    ```
    yarn run v1.22.19
    modules/enhancedEcommerceEvents.ts:297:10 - error TS2678: Type '"vtex:promotionClick"' is not comparable to type '"vtex:productView" | "vtex:productClick" | "vtex:orderPlaced" | "vtex:orderPlacedTracked" | "vtex:pageView" | "vtex:pageInfo" | "vtex:productImpression" | "vtex:addToCart" | ... 5 more ... | "vtex:promoView"'.

    297     case 'vtex:promotionClick': {
                 ~~~~~~~~~~~~~~~~~~~~~

    Found 1 error.
    ```

commit 6f20741e083cb4d8296f71e07d23b56f5c2e1a9b
Author: Filipe W. Lima <381395+filipewl@users.noreply.github.com>
Date:   Tue Apr 25 19:13:00 2023 -0300

    Fix many type errors (15 of 18) due to types missing a discriminator

    Before:
    ```
    yarn run v1.22.19
    modules/enhancedEcommerceEvents.ts:48:27 - error TS2339: Property 'list' does not exist on type 'ProductViewData | PromoViewData | PromotionClickData'.
      Property 'list' does not exist on type 'PromoViewData'.

    48       const list = e.data.list ? { actionField: { list: e.data.list } } : {}
                                 ~~~~

    modules/enhancedEcommerceEvents.ts:48:64 - error TS2339: Property 'list' does not exist on type 'ProductViewData | PromoViewData | PromotionClickData'.
      Property 'list' does not exist on type 'PromoViewData'.

    48       const list = e.data.list ? { actionField: { list: e.data.list } } : {}
                                                                      ~~~~

    modules/enhancedEcommerceEvents.ts:105:27 - error TS2339: Property 'list' does not exist on type 'ProductClickData | PromoViewData | PromotionClickData'.
      Property 'list' does not exist on type 'PromoViewData'.

    105       const list = e.data.list ? { actionField: { list: e.data.list } } : {}
                                  ~~~~

    modules/enhancedEcommerceEvents.ts:105:64 - error TS2339: Property 'list' does not exist on type 'ProductClickData | PromoViewData | PromotionClickData'.
      Property 'list' does not exist on type 'PromoViewData'.

    105       const list = e.data.list ? { actionField: { list: e.data.list } } : {}
                                                                       ~~~~

    modules/enhancedEcommerceEvents.ts:213:46 - error TS2345: Argument of type 'OrderPlacedData | PromoViewData | PromotionClickData' is not assignable to parameter of type 'Order'.
      Type 'PromoViewData' is missing the following properties from type 'Order': accountName, corporateName, coupon, openTextField, and 27 more.

    213           actionField: getPurchaseObjectData(order),
                                                     ~~~~~

    modules/enhancedEcommerceEvents.ts:214:27 - error TS2339: Property 'transactionProducts' does not exist on type 'OrderPlacedData | PromoViewData | PromotionClickData'.
      Property 'transactionProducts' does not exist on type 'PromoViewData'.

    214           products: order.transactionProducts.map((product: ProductOrder) =>
                                  ~~~~~~~~~~~~~~~~~~~

    modules/enhancedEcommerceEvents.ts:241:25 - error TS2339: Property 'list' does not exist on type 'ProductImpressionData | PromoViewData | PromotionClickData'.

    241       const { currency, list, impressions } = e.data
                                ~~~~

    modules/enhancedEcommerceEvents.ts:241:31 - error TS2339: Property 'impressions' does not exist on type 'ProductImpressionData | PromoViewData | PromotionClickData'.

    241       const { currency, list, impressions } = e.data
                                      ~~~~~~~~~~~

    modules/enhancedEcommerceEvents.ts:261:15 - error TS2339: Property 'orderForm' does not exist on type 'PromoViewData | PromotionClickData'.

    261       const { orderForm } = e.data
                      ~~~~~~~~~

    modules/extraEvents.ts:19:26 - error TS2339: Property 'pageUrl' does not exist on type 'PageViewData | PromoViewData | PromotionClickData'.
      Property 'pageUrl' does not exist on type 'PromoViewData'.

    19         location: e.data.pageUrl,
                                ~~~~~~~

    modules/extraEvents.ts:20:22 - error TS2339: Property 'pageUrl' does not exist on type 'PageViewData | PromoViewData | PromotionClickData'.
      Property 'pageUrl' does not exist on type 'PromoViewData'.

    20         page: e.data.pageUrl.replace(e.origin, ''),
                            ~~~~~~~

    modules/extraEvents.ts:21:26 - error TS2339: Property 'referrer' does not exist on type 'PageViewData | PromoViewData | PromotionClickData'.
      Property 'referrer' does not exist on type 'PromoViewData'.

    21         referrer: e.data.referrer,
                                ~~~~~~~~

    modules/extraEvents.ts:22:20 - error TS2339: Property 'pageTitle' does not exist on type 'PageViewData | PromoViewData | PromotionClickData'.
      Property 'pageTitle' does not exist on type 'PromoViewData'.

    22         ...(e.data.pageTitle && {
                          ~~~~~~~~~

    modules/extraEvents.ts:23:25 - error TS2339: Property 'pageTitle' does not exist on type 'PageViewData | PromoViewData | PromotionClickData'.
      Property 'pageTitle' does not exist on type 'PromoViewData'.

    23           title: e.data.pageTitle,
                               ~~~~~~~~~

    modules/extraEvents.ts:33:17 - error TS2339: Property 'isAuthenticated' does not exist on type 'UserData | PromoViewData | PromotionClickData'.
      Property 'isAuthenticated' does not exist on type 'PromoViewData'.

    33       if (!data.isAuthenticated) {
                       ~~~~~~~~~~~~~~~

    modules/extraEvents.ts:37:30 - error TS2339: Property 'email' does not exist on type 'UserData | PromoViewData | PromotionClickData'.
      Property 'email' does not exist on type 'PromoViewData'.

    37       const emailHash = data.email ? await emailToHash(data.email) : undefined
                                    ~~~~~

    modules/extraEvents.ts:37:61 - error TS2339: Property 'email' does not exist on type 'UserData | PromoViewData | PromotionClickData'.
      Property 'email' does not exist on type 'PromoViewData'.

    37       const emailHash = data.email ? await emailToHash(data.email) : undefined
                                                                   ~~~~~

    modules/extraEvents.ts:41:22 - error TS2339: Property 'id' does not exist on type 'UserData | PromoViewData | PromotionClickData'.
      Property 'id' does not exist on type 'PromoViewData'.

    41         userId: data.id,
                            ~~

    Found 18 errors.
    ```

    After:
    ```
    yarn run v1.22.19
    modules/enhancedEcommerceEvents.ts:260:10 - error TS2678: Type '"vtex:cartLoaded"' is not comparable to type '"vtex:productView" | "vtex:productClick" | "vtex:orderPlaced" | "vtex:orderPlacedTracked" | "vtex:pageView" | "vtex:pageInfo" | "vtex:productImpression" | "vtex:addToCart" | ... 4 more ... | "vtex:promoView"'.

    260     case 'vtex:cartLoaded': {
                 ~~~~~~~~~~~~~~~~~

    modules/enhancedEcommerceEvents.ts:270:33 - error TS2339: Property 'items' does not exist on type 'never'.

    270             products: orderForm.items.map(getCheckoutProductObjectData),
                                        ~~~~~

    modules/enhancedEcommerceEvents.ts:297:10 - error TS2678: Type '"vtex:promotionClick"' is not comparable to type '"vtex:productView" | "vtex:productClick" | "vtex:orderPlaced" | "vtex:orderPlacedTracked" | "vtex:pageView" | "vtex:pageInfo" | "vtex:productImpression" | "vtex:addToCart" | ... 4 more ... | "vtex:promoView"'.

    297     case 'vtex:promotionClick': {
                 ~~~~~~~~~~~~~~~~~~~~~

    Found 3 errors.
    ```

commit 3d87269c58ff5b4ac640ff330089ad5b725c2a40
Author: Filipe W. Lima <381395+filipewl@users.noreply.github.com>
Date:   Tue Apr 25 16:42:00 2023 -0300

    Fix a type error (1/19) in `productView` of `legacyEvents`

    ```
    modules/legacyEvents.ts:58:14 - error TS2678: Type '"productView"' is not comparable to type '"vtex:promoView" | "vtex:promotionClick" | "homeView" | "productPageInfo" | "internalSiteSearchView" | "categoryView" | "departmentView" | "emptySearchView"'.

    58         case 'productView': {
                    ~~~~~~~~~~~~~
    ```

commit c959149c8bbf45a0edac4c24425948da2ccc8b3f
Author: Filipe W. Lima <381395+filipewl@users.noreply.github.com>
Date:   Tue Apr 25 16:14:43 2023 -0300

    Removed the unused `CartData` type from the `PixelMessage` interface

    This `CartData` type isn't defined anywhere in the project so it's useless.

    Originally added [here](https://github.com/vtex-apps/google-tag-manager/pull/38/files#diff-791619406f30fb7292cdecb798d2a840d54a926399fdcd740a7706dbe852c9a6), it was later [renamed](https://github.com/vtex-apps/google-tag-manager/pull/40/files#diff-791619406f30fb7292cdecb798d2a840d54a926399fdcd740a7706dbe852c9a6) to `CartLoadedData` but `CartData` [remained](https://github.com/vtex-apps/google-tag-manager/blob/f785e969c4b947a8c699598c46bdefde3cca79a2/react/typings/events.d.ts#L17) in the `PixelMessage` list.